#!/usr/bin/env ruby
target = ARGV[0] || '~'

excludes = %w(. .. .git README.md .gitignore bootstrap)
dotfiles = Dir.entries(Dir.pwd) - excludes

dotfiles.each do |dotfile|
  link = "#{target}/#{dotfile}"
  puts "Linking #{link}"
  %x{ ln -s #{Dir.pwd}/#{dotfile} #{link} }
end

mkdir -p ~/Library/KeyBindings
cp DefaultKeyBinding.dict ~/Library/KeyBindings
