#!/usr/bin/env ruby
target = ARGV[0] || "~"

excludes = %w[. .. .config .git README.md .gitignore bootstrap]
dotfiles = Dir.entries(Dir.pwd) - excludes

dotfiles.each do |dotfile|
  link = "#{target}/#{dotfile}"
  puts "Linking #{link}"
  `ln -s #{Dir.pwd}/#{dotfile} #{link}`
end

`mkdir -p ~/Library/KeyBindings`
`cp DefaultKeyBinding.dict ~/Library/KeyBindings`
`ln -s ~/.bash_profile ~/.bashrc`
`mkdir -p ~/.config`
`ln -s #{Dir.pwd}/.config/starship.toml ~/.config/starship.toml`
