#!/usr/bin/env ruby
require 'optparse'

options = {
  :concurrency => 10
}

@parser = OptionParser.new do |opts|
  opts.banner = <<EOL
node_exec lists the current revision a rails app is running on a host.

  Usage: node_exec [options] node_name
EOL

  opts.on('-n', '--name [NAME]', "Node name to match") {|v| options[:name] = v }
  opts.on('-r', '--role [ROLE]', "Role to match") {|v| options[:role] = v }
  opts.on('-C', '--concurrency [NUM]', "Number of concurrent SSH connections") {|v| options[:concurrency] = v }
  opts.on('-e', '--environment [ENV]', "Node chef-environment to match") {|v| options[:chef_environment] = v }
  opts.on_tail("-h", "--help", "Show this message") do
    puts opts
    exit
  end
end
@parser.parse!(ARGV)

cmd_exec                      = ARGV.pop
options[:chef_environment]  ||= ARGV.pop
options[:role]              ||= ARGV.shift

identity_file = case options[:chef_environment]
  when 'production';          "~/.ec2/katama-prod.pem"
  when 'katama_production';   "~/.ec2/katama-prod.pem"
  else;                       "~/.ec2/katama-integration.pem"
end

filter_attrs = (options.keys - [:concurrency]).select {|k| options[k] }
filters = filter_attrs.map {|option| "#{option}:#{options[option]}" }
unless filters.any?
  puts "ERROR: Must specify one or more node filters"
  puts parser
  exit 1
end
cmd = "env CHEF_ENV=#{options[:chef_environment]} knife ssh -C #{options[:concurrency]} -a name -x ubuntu -i #{identity_file} '#{ filters.join(' AND ') }' '#{cmd_exec}'"
puts cmd
system("cd /work/chef; #{cmd}")